version: '3.8'

services:
  argos-prod:
    container_name: argos-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8090"]
      interval: 30s
      timeout: 10s
      retries: 3
